import type { Movement } from "./types";

// Curated movement library. Tagged so the engine can balance pulls/pushes,
// upper/lower, and modality (M/G/W) within a session.
//
// `availableIn` gates a movement to specific equipment-set filters.
// Cardio-only sets (rower_only / ski_only / bike_only / airbike_only) resolve
// to that single machine plus bodyweight — no loaded movements.

const ALL_CARDIO_ONLY = [
  "rower_only",
  "ski_only",
  "bike_only",
  "airbike_only",
] as const;

export const MOVEMENTS: Movement[] = [
  // ───────── Monostructural / Cardio ─────────
  {
    id: "row",
    name: "Row",
    modality: "M",
    pattern: "locomotion",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["rower"],
    availableIn: ["full_gym", "rower_only"],
    hyroxStation: true,
    unit: "cal",
    repsByIntensity: {
      recovery: [10, 15],
      aerobic: [12, 18],
      threshold: [15, 25],
      max_effort: [20, 30],
    },
    stimulusTags: ["cardio", "low_impact", "pull"],
  },
  {
    id: "ski",
    name: "Ski Erg",
    modality: "M",
    pattern: "pull",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["ski_erg"],
    availableIn: ["full_gym", "ski_only"],
    hyroxStation: true,
    unit: "cal",
    repsByIntensity: {
      recovery: [10, 15],
      aerobic: [12, 18],
      threshold: [15, 25],
      max_effort: [20, 30],
    },
    stimulusTags: ["cardio", "pull"],
  },
  {
    id: "bike",
    name: "Bike Erg",
    modality: "M",
    pattern: "locomotion",
    region: "lower",
    impact: "low",
    skill: 1,
    equipment: ["bike_erg"],
    availableIn: ["full_gym", "bike_only"],
    unit: "cal",
    repsByIntensity: {
      recovery: [10, 15],
      aerobic: [12, 20],
      threshold: [18, 30],
      max_effort: [25, 40],
    },
    stimulusTags: ["cardio", "low_impact"],
  },
  {
    id: "airbike",
    name: "Air Bike",
    modality: "M",
    pattern: "locomotion",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["airbike"],
    availableIn: ["full_gym", "airbike_only"],
    unit: "cal",
    repsByIntensity: {
      recovery: [8, 12],
      aerobic: [10, 15],
      threshold: [15, 25],
      max_effort: [20, 30],
    },
    stimulusTags: ["cardio", "full_body", "high_output"],
  },
  {
    id: "run",
    name: "Run",
    modality: "M",
    pattern: "locomotion",
    region: "lower",
    impact: "moderate",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      ...ALL_CARDIO_ONLY,
    ],
    hyroxStation: true,
    unit: "m",
    repsByIntensity: {
      recovery: [200, 400],
      aerobic: [400, 600],
      threshold: [400, 800],
      max_effort: [200, 400],
    },
    stimulusTags: ["cardio", "lower"],
  },
  {
    id: "shuttle",
    name: "Shuttle Run",
    modality: "M",
    pattern: "locomotion",
    region: "lower",
    impact: "high",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "m",
    repsByIntensity: {
      recovery: [40, 80],
      aerobic: [80, 120],
      threshold: [100, 200],
      max_effort: [60, 120],
    },
    stimulusTags: ["cardio", "lower", "agility"],
  },
  {
    id: "double_under",
    name: "Double-Unders",
    modality: "M",
    pattern: "locomotion",
    region: "full",
    impact: "moderate",
    skill: 3,
    equipment: ["jump_rope"],
    availableIn: ["full_gym", "bodyweight_travel"],
    unit: "reps",
    repsByIntensity: {
      recovery: [25, 40],
      aerobic: [40, 60],
      threshold: [50, 80],
      max_effort: [40, 60],
    },
    stimulusTags: ["cardio", "skill", "calves"],
  },

  // ───────── Gymnastics / Bodyweight ─────────
  {
    id: "burpee",
    name: "Burpees",
    modality: "G",
    pattern: "push",
    region: "full",
    impact: "high",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [5, 10],
      aerobic: [10, 15],
      threshold: [15, 25],
      max_effort: [10, 20],
    },
    stimulusTags: ["full_body", "cardio", "push"],
  },
  {
    id: "burpee_box_jump",
    name: "Burpee Box Jump-Overs",
    modality: "G",
    pattern: "push",
    region: "full",
    impact: "high",
    skill: 2,
    equipment: ["box"],
    availableIn: ["full_gym"],
    hyroxStation: true,
    unit: "reps",
    repsByIntensity: {
      recovery: [5, 8],
      aerobic: [8, 12],
      threshold: [10, 20],
      max_effort: [8, 15],
    },
    stimulusTags: ["full_body", "cardio", "push"],
  },
  {
    id: "pullup",
    name: "Pull-Ups",
    modality: "G",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["pullup_bar"],
    availableIn: ["full_gym", "bodyweight_travel"],
    unit: "reps",
    repsByIntensity: {
      recovery: [3, 5],
      aerobic: [5, 8],
      threshold: [8, 12],
      max_effort: [5, 10],
    },
    stimulusTags: ["pull", "upper", "vertical_pull"],
  },
  {
    id: "ttb",
    name: "Toes-to-Bar",
    modality: "G",
    pattern: "core",
    region: "full",
    impact: "low",
    skill: 4,
    equipment: ["pullup_bar"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [4, 6],
      aerobic: [6, 10],
      threshold: [8, 15],
      max_effort: [6, 12],
    },
    stimulusTags: ["core", "pull", "grip"],
  },
  {
    id: "pushup",
    name: "Push-Ups",
    modality: "G",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [8, 12],
      aerobic: [10, 15],
      threshold: [15, 25],
      max_effort: [10, 20],
    },
    stimulusTags: ["push", "upper", "horizontal_push"],
  },
  {
    id: "hspu",
    name: "Handstand Push-Ups",
    modality: "G",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 4,
    equipment: ["bodyweight"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [3, 5],
      aerobic: [5, 8],
      threshold: [6, 12],
      max_effort: [4, 8],
    },
    stimulusTags: ["push", "upper", "vertical_push", "skill"],
  },
  {
    id: "ring_row",
    name: "Ring Rows",
    modality: "G",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["rings"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [8, 12],
      aerobic: [10, 15],
      threshold: [12, 20],
      max_effort: [10, 15],
    },
    stimulusTags: ["pull", "upper", "horizontal_pull"],
  },
  {
    id: "muscle_up",
    name: "Muscle-Ups",
    modality: "G",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 5,
    equipment: ["rings"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [1, 2],
      aerobic: [2, 4],
      threshold: [3, 6],
      max_effort: [2, 5],
    },
    stimulusTags: ["pull", "push", "upper", "skill"],
  },
  {
    id: "air_squat",
    name: "Air Squats",
    modality: "G",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [15, 25],
      aerobic: [20, 30],
      threshold: [25, 50],
      max_effort: [20, 40],
    },
    stimulusTags: ["squat", "lower"],
  },
  {
    id: "pistol",
    name: "Pistol Squats",
    modality: "G",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 4,
    equipment: ["bodyweight"],
    availableIn: ["full_gym", "bodyweight_travel"],
    unit: "reps",
    repsByIntensity: {
      recovery: [4, 8],
      aerobic: [8, 12],
      threshold: [10, 16],
      max_effort: [8, 14],
    },
    stimulusTags: ["squat", "lower", "skill", "unilateral"],
  },
  {
    id: "lunge_walking",
    name: "Walking Lunges",
    modality: "G",
    pattern: "lunge",
    region: "lower",
    impact: "low",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 16],
      aerobic: [16, 24],
      threshold: [20, 30],
      max_effort: [20, 30],
    },
    stimulusTags: ["lunge", "lower", "unilateral"],
  },
  {
    id: "box_jump",
    name: "Box Jumps",
    modality: "G",
    pattern: "squat",
    region: "lower",
    impact: "high",
    skill: 2,
    equipment: ["box"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [8, 12],
      aerobic: [10, 15],
      threshold: [15, 25],
      max_effort: [10, 20],
    },
    stimulusTags: ["squat", "lower", "power"],
  },
  {
    id: "wallball",
    name: "Wall Balls",
    modality: "W",
    pattern: "squat",
    region: "full",
    impact: "moderate",
    skill: 2,
    equipment: ["wallball"],
    availableIn: ["full_gym"],
    hyroxStation: true,
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 15],
      aerobic: [15, 20],
      threshold: [20, 30],
      max_effort: [15, 25],
    },
    loadHint: "20/14 lb",
    stimulusTags: ["squat", "full_body", "push"],
  },

  // ───────── Powerlifting / Strength — Barbell ─────────
  {
    id: "back_squat",
    name: "Back Squat",
    modality: "W",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [15, 20],
      aerobic: [10, 12],
      threshold: [5, 8],
      max_effort: [1, 5],
    },
    loadHint: "heavy",
    stimulusTags: ["squat", "lower", "strength", "main_lift"],
  },
  {
    id: "bench_press",
    name: "Bench Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["barbell", "bench"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 12],
      threshold: [3, 5],
      max_effort: [1, 3],
    },
    loadHint: "heavy",
    stimulusTags: ["push", "upper", "horizontal_push", "strength", "main_lift"],
  },
  {
    id: "strict_press",
    name: "Strict Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 12],
      aerobic: [6, 10],
      threshold: [3, 5],
      max_effort: [1, 3],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["push", "upper", "vertical_push", "strength", "main_lift"],
  },
  {
    id: "pendlay_row",
    name: "Pendlay Rows",
    modality: "W",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 12],
      aerobic: [6, 10],
      threshold: [4, 6],
      max_effort: [3, 5],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["pull", "upper", "horizontal_pull", "strength"],
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 10],
      threshold: [5, 8],
      max_effort: [3, 5],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["hinge", "posterior", "strength"],
  },
  {
    id: "good_morning",
    name: "Good Mornings",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 12],
      threshold: [5, 8],
      max_effort: [3, 6],
    },
    loadHint: "moderate",
    stimulusTags: ["hinge", "posterior", "accessory"],
  },
  {
    id: "deadlift",
    name: "Deadlifts",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 12],
      aerobic: [6, 10],
      threshold: [3, 5],
      max_effort: [1, 3],
    },
    loadHint: "heavy",
    stimulusTags: ["hinge", "pull", "posterior", "strength", "main_lift"],
  },
  {
    id: "power_clean",
    name: "Power Cleans",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "moderate",
    skill: 4,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [3, 5],
      aerobic: [4, 6],
      threshold: [5, 10],
      max_effort: [3, 6],
    },
    loadHint: "moderate",
    stimulusTags: ["hinge", "pull", "power", "skill"],
  },
  {
    id: "thruster",
    name: "Thrusters",
    modality: "W",
    pattern: "squat",
    region: "full",
    impact: "moderate",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [5, 8],
      aerobic: [8, 12],
      threshold: [10, 15],
      max_effort: [5, 10],
    },
    loadHint: "95/65 lb",
    stimulusTags: ["squat", "push", "full_body"],
  },
  {
    id: "front_squat",
    name: "Front Squats",
    modality: "W",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 10],
      threshold: [5, 6],
      max_effort: [1, 3],
    },
    loadHint: "heavy",
    stimulusTags: ["squat", "lower", "strength", "main_lift"],
  },
  {
    id: "shoulder_to_oh",
    name: "Shoulder-to-Overhead",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [5, 8],
      aerobic: [6, 10],
      threshold: [8, 12],
      max_effort: [3, 6],
    },
    loadHint: "moderate",
    stimulusTags: ["push", "upper", "vertical_push"],
  },
  {
    id: "snatch",
    name: "Power Snatches",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 5,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [3, 5],
      aerobic: [4, 6],
      threshold: [5, 8],
      max_effort: [2, 5],
    },
    loadHint: "moderate",
    stimulusTags: ["pull", "power", "skill"],
  },

  // ───────── Weightlifting — Dumbbell ─────────
  {
    id: "db_bench_press",
    name: "DB Bench Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["dumbbell", "bench"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 12],
      threshold: [5, 8],
      max_effort: [3, 5],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["push", "upper", "horizontal_push", "strength", "main_lift"],
  },
  {
    id: "db_row",
    name: "DB Rows",
    modality: "W",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 12],
      threshold: [6, 10],
      max_effort: [5, 8],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["pull", "upper", "horizontal_pull", "strength"],
  },
  {
    id: "db_rdl",
    name: "DB Romanian Deadlift",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "low",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [10, 12],
      threshold: [8, 10],
      max_effort: [5, 8],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["hinge", "posterior", "strength"],
  },
  {
    id: "db_goblet_squat",
    name: "DB Goblet Squats",
    modality: "W",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 1,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [10, 12],
      threshold: [6, 10],
      max_effort: [5, 8],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["squat", "lower", "strength", "main_lift"],
  },
  {
    id: "db_snatch",
    name: "DB Snatches (alternating)",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 14],
      aerobic: [12, 18],
      threshold: [16, 24],
      max_effort: [10, 20],
    },
    loadHint: "50/35 lb",
    stimulusTags: ["pull", "full_body", "unilateral"],
  },
  {
    id: "db_thruster",
    name: "DB Thrusters",
    modality: "W",
    pattern: "squat",
    region: "full",
    impact: "moderate",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 14],
      threshold: [12, 20],
      max_effort: [8, 14],
    },
    loadHint: "50/35 lb",
    stimulusTags: ["squat", "push", "full_body"],
  },
  {
    id: "db_lunge",
    name: "DB Walking Lunges",
    modality: "W",
    pattern: "lunge",
    region: "lower",
    impact: "low",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    hyroxStation: true,
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 14],
      aerobic: [14, 20],
      threshold: [20, 30],
      max_effort: [16, 24],
    },
    loadHint: "50/35 lb",
    stimulusTags: ["lunge", "lower", "unilateral"],
  },
  {
    id: "db_push_press",
    name: "DB Push Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 12],
      threshold: [10, 16],
      max_effort: [6, 12],
    },
    loadHint: "50/35 lb",
    stimulusTags: ["push", "upper", "vertical_push"],
  },
  {
    id: "renegade_row",
    name: "DB Renegade Rows",
    modality: "W",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 12],
      threshold: [10, 16],
      max_effort: [8, 14],
    },
    loadHint: "moderate",
    stimulusTags: ["pull", "upper", "horizontal_pull", "core"],
  },

  // ───────── Weightlifting — Kettlebell ─────────
  {
    id: "kb_front_squat",
    name: "KB Front Squat (double)",
    modality: "W",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 2,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 12],
      threshold: [5, 8],
      max_effort: [3, 6],
    },
    loadHint: "2×53/35 lb",
    stimulusTags: ["squat", "lower", "strength", "main_lift"],
  },
  {
    id: "kb_floor_press",
    name: "KB Floor Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 12],
      threshold: [5, 8],
      max_effort: [3, 6],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["push", "upper", "horizontal_push", "strength", "main_lift"],
  },
  {
    id: "kb_swing",
    name: "KB Swings (American)",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "low",
    skill: 2,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 18],
      aerobic: [15, 25],
      threshold: [20, 35],
      max_effort: [15, 25],
    },
    loadHint: "53/35 lb",
    stimulusTags: ["hinge", "pull", "posterior", "power"],
  },
  {
    id: "kb_goblet_squat",
    name: "KB Goblet Squats",
    modality: "W",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 1,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 14],
      aerobic: [12, 18],
      threshold: [15, 25],
      max_effort: [10, 18],
    },
    loadHint: "53/35 lb",
    stimulusTags: ["squat", "lower"],
  },
  {
    id: "kb_clean_jerk",
    name: "KB Clean & Jerks",
    modality: "W",
    pattern: "push",
    region: "full",
    impact: "moderate",
    skill: 4,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 12],
      threshold: [10, 16],
      max_effort: [8, 14],
    },
    loadHint: "53/35 lb",
    stimulusTags: ["push", "pull", "full_body", "skill"],
  },
  {
    id: "kb_snatch",
    name: "KB Snatches",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 4,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 12],
      threshold: [10, 18],
      max_effort: [8, 14],
    },
    loadHint: "53/35 lb",
    stimulusTags: ["pull", "full_body", "skill"],
  },
  {
    id: "turkish_getup",
    name: "Turkish Get-Ups",
    modality: "W",
    pattern: "core",
    region: "full",
    impact: "low",
    skill: 4,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [2, 4],
      aerobic: [3, 5],
      threshold: [4, 6],
      max_effort: [3, 5],
    },
    loadHint: "moderate",
    stimulusTags: ["core", "skill", "stability"],
  },

  // ───────── Carries ─────────
  {
    id: "farmers_carry",
    name: "Farmer's Carry",
    modality: "W",
    pattern: "carry",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["dumbbell", "kettlebell"],
    availableIn: ["full_gym", "dumbbell_only", "kettlebell_only"],
    hyroxStation: true,
    unit: "m",
    repsByIntensity: {
      recovery: [40, 60],
      aerobic: [60, 100],
      threshold: [80, 150],
      max_effort: [60, 120],
    },
    loadHint: "heavy",
    stimulusTags: ["carry", "grip", "core"],
  },

  // ───────── Core ─────────
  {
    id: "situp",
    name: "Sit-Ups",
    modality: "G",
    pattern: "core",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [15, 25],
      aerobic: [20, 30],
      threshold: [25, 40],
      max_effort: [20, 35],
    },
    stimulusTags: ["core"],
  },
  {
    id: "plank",
    name: "Plank Hold",
    modality: "G",
    pattern: "core",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "sec",
    repsByIntensity: {
      recovery: [30, 45],
      aerobic: [40, 60],
      threshold: [45, 75],
      max_effort: [30, 60],
    },
    stimulusTags: ["core", "isometric"],
  },

  // ───────── Additional Cardio / Locomotion ─────────
  {
    id: "single_under",
    name: "Single-Unders",
    modality: "M",
    pattern: "locomotion",
    region: "full",
    impact: "moderate",
    skill: 1,
    equipment: ["jump_rope"],
    availableIn: ["full_gym", "bodyweight_travel"],
    unit: "reps",
    repsByIntensity: {
      recovery: [50, 80],
      aerobic: [80, 130],
      threshold: [100, 150],
      max_effort: [150, 250],
    },
    stimulusTags: ["cardio", "footwork"],
  },
  {
    id: "broad_jump",
    name: "Broad Jumps",
    modality: "G",
    pattern: "lunge",
    region: "lower",
    impact: "high",
    skill: 2,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 14],
      threshold: [10, 16],
      max_effort: [12, 20],
    },
    stimulusTags: ["plyo", "lower", "explosive"],
  },
  {
    id: "burpee_over_bar",
    name: "Burpees Over Bar",
    modality: "M",
    pattern: "core",
    region: "full",
    impact: "high",
    skill: 2,
    equipment: ["barbell", "bodyweight"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 14],
      threshold: [12, 20],
      max_effort: [15, 25],
    },
    stimulusTags: ["cardio", "burpee", "full"],
  },
  {
    id: "burpee_broad_jump",
    name: "Burpee Broad Jumps",
    modality: "M",
    pattern: "core",
    region: "full",
    impact: "high",
    skill: 2,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [5, 8],
      aerobic: [8, 12],
      threshold: [10, 16],
      max_effort: [12, 20],
    },
    stimulusTags: ["cardio", "burpee", "explosive"],
  },
  {
    id: "bear_crawl",
    name: "Bear Crawl",
    modality: "G",
    pattern: "locomotion",
    region: "full",
    impact: "moderate",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "m",
    repsByIntensity: {
      recovery: [20, 40],
      aerobic: [30, 60],
      threshold: [40, 80],
      max_effort: [50, 100],
    },
    stimulusTags: ["core", "locomotion"],
  },

  // ───────── Additional Gymnastics ─────────
  {
    id: "strict_pullup",
    name: "Strict Pull-Ups",
    modality: "G",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["pullup_bar", "rig"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [3, 6],
      aerobic: [4, 8],
      threshold: [5, 10],
      max_effort: [6, 12],
    },
    stimulusTags: ["pull", "upper", "strict"],
  },
  {
    id: "chest_to_bar",
    name: "Chest-to-Bar Pull-Ups",
    modality: "G",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 4,
    equipment: ["pullup_bar", "rig"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [3, 6],
      aerobic: [5, 10],
      threshold: [8, 14],
      max_effort: [10, 18],
    },
    stimulusTags: ["pull", "upper", "kipping"],
  },
  {
    id: "bar_muscle_up",
    name: "Bar Muscle-Ups",
    modality: "G",
    pattern: "pull",
    region: "upper",
    impact: "moderate",
    skill: 5,
    equipment: ["pullup_bar", "rig"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [2, 4],
      aerobic: [3, 6],
      threshold: [4, 8],
      max_effort: [5, 10],
    },
    stimulusTags: ["pull", "upper", "explosive"],
  },
  {
    id: "ring_dip",
    name: "Ring Dips",
    modality: "G",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 4,
    equipment: ["rings"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [3, 6],
      aerobic: [5, 10],
      threshold: [8, 14],
      max_effort: [10, 18],
    },
    stimulusTags: ["push", "upper", "rings"],
  },
  {
    id: "bar_dip",
    name: "Bar Dips",
    modality: "G",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["rig", "bench"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [4, 8],
      aerobic: [6, 12],
      threshold: [10, 16],
      max_effort: [12, 20],
    },
    stimulusTags: ["push", "upper"],
  },
  {
    id: "strict_hspu",
    name: "Strict Handstand Push-Ups",
    modality: "G",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 5,
    equipment: ["bodyweight"],
    availableIn: ["full_gym", "bodyweight_travel"],
    unit: "reps",
    repsByIntensity: {
      recovery: [2, 4],
      aerobic: [3, 6],
      threshold: [4, 8],
      max_effort: [5, 10],
    },
    stimulusTags: ["push", "upper", "strict", "inversion"],
  },
  {
    id: "pike_pushup",
    name: "Pike Push-Ups",
    modality: "G",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [5, 10],
      aerobic: [8, 14],
      threshold: [10, 18],
      max_effort: [12, 22],
    },
    stimulusTags: ["push", "upper"],
  },
  {
    id: "handstand_walk",
    name: "Handstand Walk",
    modality: "G",
    pattern: "locomotion",
    region: "upper",
    impact: "moderate",
    skill: 5,
    equipment: ["bodyweight"],
    availableIn: ["full_gym", "bodyweight_travel"],
    unit: "m",
    repsByIntensity: {
      recovery: [3, 8],
      aerobic: [5, 12],
      threshold: [8, 18],
      max_effort: [10, 25],
    },
    stimulusTags: ["upper", "inversion", "balance"],
  },
  {
    id: "hollow_rock",
    name: "Hollow Rocks",
    modality: "G",
    pattern: "core",
    region: "full",
    impact: "low",
    skill: 2,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 20],
      aerobic: [15, 25],
      threshold: [20, 35],
      max_effort: [25, 40],
    },
    stimulusTags: ["core", "isometric"],
  },
  {
    id: "v_up",
    name: "V-Ups",
    modality: "G",
    pattern: "core",
    region: "full",
    impact: "low",
    skill: 2,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [8, 14],
      aerobic: [12, 20],
      threshold: [15, 25],
      max_effort: [20, 35],
    },
    stimulusTags: ["core"],
  },
  {
    id: "knees_to_elbows",
    name: "Knees-to-Elbows",
    modality: "G",
    pattern: "core",
    region: "full",
    impact: "low",
    skill: 3,
    equipment: ["pullup_bar", "rig"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [5, 10],
      aerobic: [8, 14],
      threshold: [10, 18],
      max_effort: [12, 22],
    },
    stimulusTags: ["core", "kipping"],
  },
  {
    id: "ghd_situp",
    name: "GHD Sit-Ups",
    modality: "G",
    pattern: "core",
    region: "full",
    impact: "moderate",
    skill: 3,
    equipment: ["bench"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [8, 14],
      aerobic: [10, 18],
      threshold: [15, 25],
      max_effort: [20, 35],
    },
    stimulusTags: ["core", "ghd"],
  },
  {
    id: "rope_climb",
    name: "Rope Climb",
    modality: "G",
    pattern: "pull",
    region: "full",
    impact: "low",
    skill: 4,
    equipment: ["rig"],
    availableIn: ["full_gym"],
    hyroxStation: false,
    unit: "reps",
    repsByIntensity: {
      recovery: [1, 2],
      aerobic: [2, 3],
      threshold: [2, 4],
      max_effort: [3, 5],
    },
    stimulusTags: ["pull", "full", "grip"],
  },
  {
    id: "l_sit_hold",
    name: "L-Sit Hold",
    modality: "G",
    pattern: "core",
    region: "full",
    impact: "low",
    skill: 4,
    equipment: ["rings", "rig"],
    availableIn: ["full_gym"],
    unit: "sec",
    repsByIntensity: {
      recovery: [10, 20],
      aerobic: [15, 30],
      threshold: [20, 40],
      max_effort: [25, 50],
    },
    stimulusTags: ["core", "isometric"],
  },

  // ───────── Additional Olympic / Barbell ─────────
  {
    id: "hang_power_clean",
    name: "Hang Power Clean",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    loadHint: "115/75 lb",
    repsByIntensity: {
      recovery: [5, 8],
      aerobic: [6, 10],
      threshold: [8, 12],
      max_effort: [10, 15],
    },
    stimulusTags: ["pull", "olympic", "full", "explosive"],
  },
  {
    id: "squat_clean",
    name: "Squat Clean",
    modality: "W",
    pattern: "squat",
    region: "full",
    impact: "moderate",
    skill: 4,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    loadHint: "135/95 lb",
    repsByIntensity: {
      recovery: [3, 5],
      aerobic: [4, 7],
      threshold: [5, 9],
      max_effort: [7, 12],
    },
    stimulusTags: ["squat", "olympic", "full", "explosive"],
  },
  {
    id: "power_snatch",
    name: "Power Snatch",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 4,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    loadHint: "95/65 lb",
    repsByIntensity: {
      recovery: [3, 5],
      aerobic: [5, 8],
      threshold: [6, 10],
      max_effort: [8, 12],
    },
    stimulusTags: ["pull", "olympic", "full", "explosive"],
  },
  {
    id: "squat_snatch",
    name: "Squat Snatch",
    modality: "W",
    pattern: "squat",
    region: "full",
    impact: "moderate",
    skill: 5,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    loadHint: "115/75 lb",
    repsByIntensity: {
      recovery: [2, 4],
      aerobic: [3, 5],
      threshold: [4, 7],
      max_effort: [5, 9],
    },
    stimulusTags: ["squat", "olympic", "full", "explosive"],
  },
  {
    id: "overhead_squat",
    name: "Overhead Squat",
    modality: "W",
    pattern: "squat",
    region: "full",
    impact: "low",
    skill: 4,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    loadHint: "95/65 lb",
    repsByIntensity: {
      recovery: [5, 8],
      aerobic: [6, 10],
      threshold: [8, 12],
      max_effort: [10, 15],
    },
    stimulusTags: ["squat", "olympic", "main_lift", "lower"],
  },
  {
    id: "push_press",
    name: "Push Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    loadHint: "115/75 lb",
    repsByIntensity: {
      recovery: [5, 8],
      aerobic: [6, 10],
      threshold: [8, 14],
      max_effort: [10, 16],
    },
    stimulusTags: ["push", "upper", "main_lift"],
  },
  {
    id: "push_jerk",
    name: "Push Jerk",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    loadHint: "135/95 lb",
    repsByIntensity: {
      recovery: [4, 7],
      aerobic: [5, 8],
      threshold: [7, 12],
      max_effort: [8, 14],
    },
    stimulusTags: ["push", "upper", "olympic", "explosive"],
  },
  {
    id: "split_jerk",
    name: "Split Jerk",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 4,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    loadHint: "155/105 lb",
    repsByIntensity: {
      recovery: [3, 5],
      aerobic: [4, 7],
      threshold: [5, 9],
      max_effort: [6, 10],
    },
    stimulusTags: ["push", "upper", "olympic", "explosive"],
  },
  {
    id: "clean_and_jerk",
    name: "Clean & Jerk",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 4,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    loadHint: "135/95 lb",
    repsByIntensity: {
      recovery: [3, 5],
      aerobic: [4, 7],
      threshold: [5, 9],
      max_effort: [7, 12],
    },
    stimulusTags: ["pull", "push", "olympic", "full", "main_lift"],
  },
  {
    id: "sumo_deadlift",
    name: "Sumo Deadlift",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "low",
    skill: 2,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    loadHint: "185/125 lb",
    repsByIntensity: {
      recovery: [5, 8],
      aerobic: [6, 10],
      threshold: [5, 8],
      max_effort: [3, 6],
    },
    stimulusTags: ["hinge", "main_lift", "lower"],
  },
  {
    id: "sdhp",
    name: "Sumo Deadlift High Pull",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    loadHint: "95/65 lb",
    repsByIntensity: {
      recovery: [8, 12],
      aerobic: [10, 15],
      threshold: [12, 20],
      max_effort: [15, 25],
    },
    stimulusTags: ["pull", "full", "explosive"],
  },
  {
    id: "bent_over_row",
    name: "Bent-Over Row",
    modality: "W",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    loadHint: "115/75 lb",
    repsByIntensity: {
      recovery: [8, 12],
      aerobic: [10, 15],
      threshold: [8, 12],
      max_effort: [6, 10],
    },
    stimulusTags: ["pull", "upper"],
  },

  // ───────── Additional Dumbbell ─────────
  {
    id: "db_clean",
    name: "Dumbbell Clean",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    loadHint: "50/35 lb DBs",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 12],
      threshold: [10, 15],
      max_effort: [12, 20],
    },
    stimulusTags: ["pull", "full", "explosive"],
  },
  {
    id: "db_devil_press",
    name: "DB Devil Press",
    modality: "W",
    pattern: "push",
    region: "full",
    impact: "high",
    skill: 3,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    loadHint: "50/35 lb DBs",
    repsByIntensity: {
      recovery: [4, 7],
      aerobic: [6, 10],
      threshold: [8, 14],
      max_effort: [10, 18],
    },
    stimulusTags: ["push", "burpee", "full", "cardio"],
  },
  {
    id: "db_man_maker",
    name: "DB Man Makers",
    modality: "W",
    pattern: "push",
    region: "full",
    impact: "moderate",
    skill: 3,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    loadHint: "35/25 lb DBs",
    repsByIntensity: {
      recovery: [4, 6],
      aerobic: [5, 8],
      threshold: [6, 10],
      max_effort: [8, 12],
    },
    stimulusTags: ["push", "pull", "full"],
  },
  {
    id: "db_box_step_up",
    name: "DB Box Step-Ups",
    modality: "W",
    pattern: "lunge",
    region: "lower",
    impact: "moderate",
    skill: 1,
    equipment: ["dumbbell", "box"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    loadHint: "50/35 lb DBs",
    repsByIntensity: {
      recovery: [10, 16],
      aerobic: [16, 24],
      threshold: [20, 30],
      max_effort: [24, 40],
    },
    stimulusTags: ["lunge", "lower", "loaded_carry"],
  },
  {
    id: "db_walking_lunge",
    name: "DB Walking Lunges",
    modality: "W",
    pattern: "lunge",
    region: "lower",
    impact: "moderate",
    skill: 1,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    loadHint: "50/35 lb DBs",
    repsByIntensity: {
      recovery: [12, 20],
      aerobic: [16, 24],
      threshold: [20, 30],
      max_effort: [24, 40],
    },
    stimulusTags: ["lunge", "lower"],
  },
  {
    id: "db_floor_press",
    name: "DB Floor Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 1,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    loadHint: "50/35 lb DBs",
    repsByIntensity: {
      recovery: [8, 12],
      aerobic: [10, 15],
      threshold: [8, 12],
      max_effort: [6, 10],
    },
    stimulusTags: ["push", "upper"],
  },
  {
    id: "db_hang_snatch",
    name: "DB Hang Snatch",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    loadHint: "50/35 lb",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [10, 14],
      threshold: [12, 20],
      max_effort: [16, 25],
    },
    stimulusTags: ["pull", "full", "explosive"],
  },

  // ───────── Additional Kettlebell ─────────
  {
    id: "kb_clean",
    name: "Kettlebell Clean",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 2,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    loadHint: "53/35 lb",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 14],
      threshold: [10, 18],
      max_effort: [12, 20],
    },
    stimulusTags: ["pull", "full", "explosive"],
  },
  {
    id: "kb_press",
    name: "Kettlebell Strict Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    loadHint: "44/26 lb",
    repsByIntensity: {
      recovery: [5, 8],
      aerobic: [6, 10],
      threshold: [5, 9],
      max_effort: [4, 7],
    },
    stimulusTags: ["push", "upper", "strict"],
  },
  {
    id: "kb_swing_american",
    name: "Kettlebell Swing (American)",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "low",
    skill: 2,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    loadHint: "53/35 lb",
    repsByIntensity: {
      recovery: [10, 15],
      aerobic: [15, 25],
      threshold: [20, 30],
      max_effort: [25, 40],
    },
    stimulusTags: ["hinge", "full", "explosive"],
  },

  // ───────── Carries ─────────
  {
    id: "suitcase_carry",
    name: "Suitcase Carry",
    modality: "W",
    pattern: "carry",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["dumbbell", "kettlebell"],
    availableIn: ["full_gym", "dumbbell_only", "kettlebell_only"],
    unit: "m",
    loadHint: "70/50 lb",
    repsByIntensity: {
      recovery: [20, 40],
      aerobic: [30, 60],
      threshold: [40, 80],
      max_effort: [50, 100],
    },
    stimulusTags: ["carry", "core", "grip"],
  },
  {
    id: "overhead_carry",
    name: "Overhead Carry",
    modality: "W",
    pattern: "carry",
    region: "full",
    impact: "low",
    skill: 2,
    equipment: ["dumbbell", "kettlebell"],
    availableIn: ["full_gym", "dumbbell_only", "kettlebell_only"],
    unit: "m",
    loadHint: "35/25 lb",
    repsByIntensity: {
      recovery: [15, 30],
      aerobic: [20, 50],
      threshold: [30, 60],
      max_effort: [40, 80],
    },
    stimulusTags: ["carry", "upper", "core"],
  },
  {
    id: "sandbag_carry",
    name: "Sandbag Bear-Hug Carry",
    modality: "W",
    pattern: "carry",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["dumbbell"],
    availableIn: ["full_gym"],
    unit: "m",
    loadHint: "100/70 lb",
    repsByIntensity: {
      recovery: [15, 30],
      aerobic: [25, 50],
      threshold: [40, 80],
      max_effort: [50, 100],
    },
    stimulusTags: ["carry", "full"],
  },

  // ───────── Plyometric / Box ─────────
  {
    id: "box_jump_over",
    name: "Box Jump-Overs",
    modality: "G",
    pattern: "lunge",
    region: "lower",
    impact: "high",
    skill: 2,
    equipment: ["box"],
    availableIn: ["full_gym"],
    hyroxStation: false,
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [10, 16],
      threshold: [12, 20],
      max_effort: [15, 25],
    },
    stimulusTags: ["plyo", "lower", "explosive"],
  },
  {
    id: "box_step_up",
    name: "Box Step-Ups",
    modality: "G",
    pattern: "lunge",
    region: "lower",
    impact: "low",
    skill: 1,
    equipment: ["box"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 20],
      aerobic: [16, 26],
      threshold: [20, 30],
      max_effort: [24, 40],
    },
    stimulusTags: ["lower", "lunge"],
  },
];

export const MOVEMENT_BY_ID: Record<string, Movement> = MOVEMENTS.reduce(
  (acc, m) => {
    acc[m.id] = m;
    return acc;
  },
  {} as Record<string, Movement>
);

// Tag-based lookups used by the engine.
export function isMainLift(m: Movement): boolean {
  return m.stimulusTags.includes("main_lift");
}

export function isCardio(m: Movement): boolean {
  return m.modality === "M" || m.stimulusTags.includes("cardio");
}
