import type { Movement } from "./types";

// Curated movement library. Tagged so the engine can balance pulls/pushes,
// upper/lower, and modality (M/G/W) within a session.
//
// `availableIn` gates a movement to specific equipment-set filters.
// Cardio-only sets (rower_only / ski_only / bike_only / airbike_only) resolve
// to that single machine plus bodyweight — no loaded movements.

const ALL_CARDIO_ONLY = [
  "rower_only",
  "ski_only",
  "bike_only",
  "airbike_only",
] as const;

export const MOVEMENTS: Movement[] = [
  // ───────── Monostructural / Cardio ─────────
  {
    id: "row",
    name: "Row",
    modality: "M",
    pattern: "locomotion",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["rower"],
    availableIn: ["full_gym", "rower_only"],
    hyroxStation: true,
    unit: "cal",
    repsByIntensity: {
      recovery: [10, 15],
      aerobic: [12, 18],
      threshold: [15, 25],
      max_effort: [20, 30],
    },
    stimulusTags: ["cardio", "low_impact", "pull"],
  },
  {
    id: "ski",
    name: "Ski Erg",
    modality: "M",
    pattern: "pull",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["ski_erg"],
    availableIn: ["full_gym", "ski_only"],
    hyroxStation: true,
    unit: "cal",
    repsByIntensity: {
      recovery: [10, 15],
      aerobic: [12, 18],
      threshold: [15, 25],
      max_effort: [20, 30],
    },
    stimulusTags: ["cardio", "pull"],
  },
  {
    id: "bike",
    name: "Bike Erg",
    modality: "M",
    pattern: "locomotion",
    region: "lower",
    impact: "low",
    skill: 1,
    equipment: ["bike_erg"],
    availableIn: ["full_gym", "bike_only"],
    unit: "cal",
    repsByIntensity: {
      recovery: [10, 15],
      aerobic: [12, 20],
      threshold: [18, 30],
      max_effort: [25, 40],
    },
    stimulusTags: ["cardio", "low_impact"],
  },
  {
    id: "airbike",
    name: "Air Bike",
    modality: "M",
    pattern: "locomotion",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["airbike"],
    availableIn: ["full_gym", "airbike_only"],
    unit: "cal",
    repsByIntensity: {
      recovery: [8, 12],
      aerobic: [10, 15],
      threshold: [15, 25],
      max_effort: [20, 30],
    },
    stimulusTags: ["cardio", "full_body", "high_output"],
  },
  {
    id: "run",
    name: "Run",
    modality: "M",
    pattern: "locomotion",
    region: "lower",
    impact: "moderate",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      ...ALL_CARDIO_ONLY,
    ],
    hyroxStation: true,
    unit: "m",
    repsByIntensity: {
      recovery: [200, 400],
      aerobic: [400, 600],
      threshold: [400, 800],
      max_effort: [200, 400],
    },
    stimulusTags: ["cardio", "lower"],
  },
  {
    id: "shuttle",
    name: "Shuttle Run",
    modality: "M",
    pattern: "locomotion",
    region: "lower",
    impact: "high",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "m",
    repsByIntensity: {
      recovery: [40, 80],
      aerobic: [80, 120],
      threshold: [100, 200],
      max_effort: [60, 120],
    },
    stimulusTags: ["cardio", "lower", "agility"],
  },
  {
    id: "double_under",
    name: "Double-Unders",
    modality: "M",
    pattern: "locomotion",
    region: "full",
    impact: "moderate",
    skill: 3,
    equipment: ["jump_rope"],
    availableIn: ["full_gym", "bodyweight_travel"],
    unit: "reps",
    repsByIntensity: {
      recovery: [25, 40],
      aerobic: [40, 60],
      threshold: [50, 80],
      max_effort: [40, 60],
    },
    stimulusTags: ["cardio", "skill", "calves"],
  },

  // ───────── Gymnastics / Bodyweight ─────────
  {
    id: "burpee",
    name: "Burpees",
    modality: "G",
    pattern: "push",
    region: "full",
    impact: "high",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [5, 10],
      aerobic: [10, 15],
      threshold: [15, 25],
      max_effort: [10, 20],
    },
    stimulusTags: ["full_body", "cardio", "push"],
  },
  {
    id: "burpee_box_jump",
    name: "Burpee Box Jump-Overs",
    modality: "G",
    pattern: "push",
    region: "full",
    impact: "high",
    skill: 2,
    equipment: ["box"],
    availableIn: ["full_gym"],
    hyroxStation: true,
    unit: "reps",
    repsByIntensity: {
      recovery: [5, 8],
      aerobic: [8, 12],
      threshold: [10, 20],
      max_effort: [8, 15],
    },
    stimulusTags: ["full_body", "cardio", "push"],
  },
  {
    id: "pullup",
    name: "Pull-Ups",
    modality: "G",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["pullup_bar"],
    availableIn: ["full_gym", "bodyweight_travel"],
    unit: "reps",
    repsByIntensity: {
      recovery: [3, 5],
      aerobic: [5, 8],
      threshold: [8, 12],
      max_effort: [5, 10],
    },
    stimulusTags: ["pull", "upper", "vertical_pull"],
  },
  {
    id: "ttb",
    name: "Toes-to-Bar",
    modality: "G",
    pattern: "core",
    region: "full",
    impact: "low",
    skill: 4,
    equipment: ["pullup_bar"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [4, 6],
      aerobic: [6, 10],
      threshold: [8, 15],
      max_effort: [6, 12],
    },
    stimulusTags: ["core", "pull", "grip"],
  },
  {
    id: "pushup",
    name: "Push-Ups",
    modality: "G",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [8, 12],
      aerobic: [10, 15],
      threshold: [15, 25],
      max_effort: [10, 20],
    },
    stimulusTags: ["push", "upper", "horizontal_push"],
  },
  {
    id: "hspu",
    name: "Handstand Push-Ups",
    modality: "G",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 4,
    equipment: ["bodyweight"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [3, 5],
      aerobic: [5, 8],
      threshold: [6, 12],
      max_effort: [4, 8],
    },
    stimulusTags: ["push", "upper", "vertical_push", "skill"],
  },
  {
    id: "ring_row",
    name: "Ring Rows",
    modality: "G",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["rings"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [8, 12],
      aerobic: [10, 15],
      threshold: [12, 20],
      max_effort: [10, 15],
    },
    stimulusTags: ["pull", "upper", "horizontal_pull"],
  },
  {
    id: "muscle_up",
    name: "Muscle-Ups",
    modality: "G",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 5,
    equipment: ["rings"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [1, 2],
      aerobic: [2, 4],
      threshold: [3, 6],
      max_effort: [2, 5],
    },
    stimulusTags: ["pull", "push", "upper", "skill"],
  },
  {
    id: "air_squat",
    name: "Air Squats",
    modality: "G",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [15, 25],
      aerobic: [20, 30],
      threshold: [25, 50],
      max_effort: [20, 40],
    },
    stimulusTags: ["squat", "lower"],
  },
  {
    id: "pistol",
    name: "Pistol Squats",
    modality: "G",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 4,
    equipment: ["bodyweight"],
    availableIn: ["full_gym", "bodyweight_travel"],
    unit: "reps",
    repsByIntensity: {
      recovery: [4, 8],
      aerobic: [8, 12],
      threshold: [10, 16],
      max_effort: [8, 14],
    },
    stimulusTags: ["squat", "lower", "skill", "unilateral"],
  },
  {
    id: "lunge_walking",
    name: "Walking Lunges",
    modality: "G",
    pattern: "lunge",
    region: "lower",
    impact: "low",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 16],
      aerobic: [16, 24],
      threshold: [20, 30],
      max_effort: [20, 30],
    },
    stimulusTags: ["lunge", "lower", "unilateral"],
  },
  {
    id: "box_jump",
    name: "Box Jumps",
    modality: "G",
    pattern: "squat",
    region: "lower",
    impact: "high",
    skill: 2,
    equipment: ["box"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [8, 12],
      aerobic: [10, 15],
      threshold: [15, 25],
      max_effort: [10, 20],
    },
    stimulusTags: ["squat", "lower", "power"],
  },
  {
    id: "wallball",
    name: "Wall Balls",
    modality: "W",
    pattern: "squat",
    region: "full",
    impact: "moderate",
    skill: 2,
    equipment: ["wallball"],
    availableIn: ["full_gym"],
    hyroxStation: true,
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 15],
      aerobic: [15, 20],
      threshold: [20, 30],
      max_effort: [15, 25],
    },
    loadHint: "20/14 lb",
    stimulusTags: ["squat", "full_body", "push"],
  },

  // ───────── Powerlifting / Strength — Barbell ─────────
  {
    id: "back_squat",
    name: "Back Squat",
    modality: "W",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [15, 20],
      aerobic: [10, 12],
      threshold: [5, 8],
      max_effort: [1, 5],
    },
    loadHint: "heavy",
    stimulusTags: ["squat", "lower", "strength", "main_lift"],
  },
  {
    id: "bench_press",
    name: "Bench Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["barbell", "bench"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 12],
      threshold: [3, 5],
      max_effort: [1, 3],
    },
    loadHint: "heavy",
    stimulusTags: ["push", "upper", "horizontal_push", "strength", "main_lift"],
  },
  {
    id: "strict_press",
    name: "Strict Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 12],
      aerobic: [6, 10],
      threshold: [3, 5],
      max_effort: [1, 3],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["push", "upper", "vertical_push", "strength", "main_lift"],
  },
  {
    id: "pendlay_row",
    name: "Pendlay Rows",
    modality: "W",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 12],
      aerobic: [6, 10],
      threshold: [4, 6],
      max_effort: [3, 5],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["pull", "upper", "horizontal_pull", "strength"],
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 10],
      threshold: [5, 8],
      max_effort: [3, 5],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["hinge", "posterior", "strength"],
  },
  {
    id: "good_morning",
    name: "Good Mornings",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 12],
      threshold: [5, 8],
      max_effort: [3, 6],
    },
    loadHint: "moderate",
    stimulusTags: ["hinge", "posterior", "accessory"],
  },
  {
    id: "deadlift",
    name: "Deadlifts",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 12],
      aerobic: [6, 10],
      threshold: [3, 5],
      max_effort: [1, 3],
    },
    loadHint: "heavy",
    stimulusTags: ["hinge", "pull", "posterior", "strength", "main_lift"],
  },
  {
    id: "power_clean",
    name: "Power Cleans",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "moderate",
    skill: 4,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [3, 5],
      aerobic: [4, 6],
      threshold: [5, 10],
      max_effort: [3, 6],
    },
    loadHint: "moderate",
    stimulusTags: ["hinge", "pull", "power", "skill"],
  },
  {
    id: "thruster",
    name: "Thrusters",
    modality: "W",
    pattern: "squat",
    region: "full",
    impact: "moderate",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [5, 8],
      aerobic: [8, 12],
      threshold: [10, 15],
      max_effort: [5, 10],
    },
    loadHint: "95/65 lb",
    stimulusTags: ["squat", "push", "full_body"],
  },
  {
    id: "front_squat",
    name: "Front Squats",
    modality: "W",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 10],
      threshold: [5, 6],
      max_effort: [1, 3],
    },
    loadHint: "heavy",
    stimulusTags: ["squat", "lower", "strength", "main_lift"],
  },
  {
    id: "shoulder_to_oh",
    name: "Shoulder-to-Overhead",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [5, 8],
      aerobic: [6, 10],
      threshold: [8, 12],
      max_effort: [3, 6],
    },
    loadHint: "moderate",
    stimulusTags: ["push", "upper", "vertical_push"],
  },
  {
    id: "snatch",
    name: "Power Snatches",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 5,
    equipment: ["barbell"],
    availableIn: ["full_gym"],
    unit: "reps",
    repsByIntensity: {
      recovery: [3, 5],
      aerobic: [4, 6],
      threshold: [5, 8],
      max_effort: [2, 5],
    },
    loadHint: "moderate",
    stimulusTags: ["pull", "power", "skill"],
  },

  // ───────── Weightlifting — Dumbbell ─────────
  {
    id: "db_bench_press",
    name: "DB Bench Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["dumbbell", "bench"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 12],
      threshold: [5, 8],
      max_effort: [3, 5],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["push", "upper", "horizontal_push", "strength", "main_lift"],
  },
  {
    id: "db_row",
    name: "DB Rows",
    modality: "W",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 12],
      threshold: [6, 10],
      max_effort: [5, 8],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["pull", "upper", "horizontal_pull", "strength"],
  },
  {
    id: "db_rdl",
    name: "DB Romanian Deadlift",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "low",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [10, 12],
      threshold: [8, 10],
      max_effort: [5, 8],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["hinge", "posterior", "strength"],
  },
  {
    id: "db_goblet_squat",
    name: "DB Goblet Squats",
    modality: "W",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 1,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [10, 12],
      threshold: [6, 10],
      max_effort: [5, 8],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["squat", "lower", "strength", "main_lift"],
  },
  {
    id: "db_snatch",
    name: "DB Snatches (alternating)",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 14],
      aerobic: [12, 18],
      threshold: [16, 24],
      max_effort: [10, 20],
    },
    loadHint: "50/35 lb",
    stimulusTags: ["pull", "full_body", "unilateral"],
  },
  {
    id: "db_thruster",
    name: "DB Thrusters",
    modality: "W",
    pattern: "squat",
    region: "full",
    impact: "moderate",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 14],
      threshold: [12, 20],
      max_effort: [8, 14],
    },
    loadHint: "50/35 lb",
    stimulusTags: ["squat", "push", "full_body"],
  },
  {
    id: "db_lunge",
    name: "DB Walking Lunges",
    modality: "W",
    pattern: "lunge",
    region: "lower",
    impact: "low",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    hyroxStation: true,
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 14],
      aerobic: [14, 20],
      threshold: [20, 30],
      max_effort: [16, 24],
    },
    loadHint: "50/35 lb",
    stimulusTags: ["lunge", "lower", "unilateral"],
  },
  {
    id: "db_push_press",
    name: "DB Push Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 12],
      threshold: [10, 16],
      max_effort: [6, 12],
    },
    loadHint: "50/35 lb",
    stimulusTags: ["push", "upper", "vertical_push"],
  },
  {
    id: "renegade_row",
    name: "DB Renegade Rows",
    modality: "W",
    pattern: "pull",
    region: "upper",
    impact: "low",
    skill: 3,
    equipment: ["dumbbell"],
    availableIn: ["full_gym", "dumbbell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 12],
      threshold: [10, 16],
      max_effort: [8, 14],
    },
    loadHint: "moderate",
    stimulusTags: ["pull", "upper", "horizontal_pull", "core"],
  },

  // ───────── Weightlifting — Kettlebell ─────────
  {
    id: "kb_front_squat",
    name: "KB Front Squat (double)",
    modality: "W",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 2,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 12],
      threshold: [5, 8],
      max_effort: [3, 6],
    },
    loadHint: "2×53/35 lb",
    stimulusTags: ["squat", "lower", "strength", "main_lift"],
  },
  {
    id: "kb_floor_press",
    name: "KB Floor Press",
    modality: "W",
    pattern: "push",
    region: "upper",
    impact: "low",
    skill: 2,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 15],
      aerobic: [8, 12],
      threshold: [5, 8],
      max_effort: [3, 6],
    },
    loadHint: "moderate-heavy",
    stimulusTags: ["push", "upper", "horizontal_push", "strength", "main_lift"],
  },
  {
    id: "kb_swing",
    name: "KB Swings (American)",
    modality: "W",
    pattern: "hinge",
    region: "full",
    impact: "low",
    skill: 2,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [12, 18],
      aerobic: [15, 25],
      threshold: [20, 35],
      max_effort: [15, 25],
    },
    loadHint: "53/35 lb",
    stimulusTags: ["hinge", "pull", "posterior", "power"],
  },
  {
    id: "kb_goblet_squat",
    name: "KB Goblet Squats",
    modality: "W",
    pattern: "squat",
    region: "lower",
    impact: "low",
    skill: 1,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [10, 14],
      aerobic: [12, 18],
      threshold: [15, 25],
      max_effort: [10, 18],
    },
    loadHint: "53/35 lb",
    stimulusTags: ["squat", "lower"],
  },
  {
    id: "kb_clean_jerk",
    name: "KB Clean & Jerks",
    modality: "W",
    pattern: "push",
    region: "full",
    impact: "moderate",
    skill: 4,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 12],
      threshold: [10, 16],
      max_effort: [8, 14],
    },
    loadHint: "53/35 lb",
    stimulusTags: ["push", "pull", "full_body", "skill"],
  },
  {
    id: "kb_snatch",
    name: "KB Snatches",
    modality: "W",
    pattern: "pull",
    region: "full",
    impact: "moderate",
    skill: 4,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [6, 10],
      aerobic: [8, 12],
      threshold: [10, 18],
      max_effort: [8, 14],
    },
    loadHint: "53/35 lb",
    stimulusTags: ["pull", "full_body", "skill"],
  },
  {
    id: "turkish_getup",
    name: "Turkish Get-Ups",
    modality: "W",
    pattern: "core",
    region: "full",
    impact: "low",
    skill: 4,
    equipment: ["kettlebell"],
    availableIn: ["full_gym", "kettlebell_only"],
    unit: "reps",
    repsByIntensity: {
      recovery: [2, 4],
      aerobic: [3, 5],
      threshold: [4, 6],
      max_effort: [3, 5],
    },
    loadHint: "moderate",
    stimulusTags: ["core", "skill", "stability"],
  },

  // ───────── Carries ─────────
  {
    id: "farmers_carry",
    name: "Farmer's Carry",
    modality: "W",
    pattern: "carry",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["dumbbell", "kettlebell"],
    availableIn: ["full_gym", "dumbbell_only", "kettlebell_only"],
    hyroxStation: true,
    unit: "m",
    repsByIntensity: {
      recovery: [40, 60],
      aerobic: [60, 100],
      threshold: [80, 150],
      max_effort: [60, 120],
    },
    loadHint: "heavy",
    stimulusTags: ["carry", "grip", "core"],
  },

  // ───────── Core ─────────
  {
    id: "situp",
    name: "Sit-Ups",
    modality: "G",
    pattern: "core",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "reps",
    repsByIntensity: {
      recovery: [15, 25],
      aerobic: [20, 30],
      threshold: [25, 40],
      max_effort: [20, 35],
    },
    stimulusTags: ["core"],
  },
  {
    id: "plank",
    name: "Plank Hold",
    modality: "G",
    pattern: "core",
    region: "full",
    impact: "low",
    skill: 1,
    equipment: ["bodyweight"],
    availableIn: [
      "full_gym",
      "bodyweight_travel",
      "kettlebell_only",
      "dumbbell_only",
      ...ALL_CARDIO_ONLY,
    ],
    unit: "sec",
    repsByIntensity: {
      recovery: [30, 45],
      aerobic: [40, 60],
      threshold: [45, 75],
      max_effort: [30, 60],
    },
    stimulusTags: ["core", "isometric"],
  },
];

export const MOVEMENT_BY_ID: Record<string, Movement> = MOVEMENTS.reduce(
  (acc, m) => {
    acc[m.id] = m;
    return acc;
  },
  {} as Record<string, Movement>
);

// Tag-based lookups used by the engine.
export function isMainLift(m: Movement): boolean {
  return m.stimulusTags.includes("main_lift");
}

export function isCardio(m: Movement): boolean {
  return m.modality === "M" || m.stimulusTags.includes("cardio");
}
